# fly.toml app configuration file generated for cabourotte-prod on 2024-10-27T20:14:29+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cabourotte-prod'
primary_region = 'cdg'

[env]
  PORT = '9013'

[experimental]
  exec = ["cabourotte", "daemon", "--config=/config/config.yaml"]

[deploy]
  strategy = "immediate"

[http_service]
  internal_port = 9013
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[files]]
guest_path = "/config/config.yaml"
local_path = "./config.prod.yaml"
processes = ["app"]

[[vm]]
  size = 'shared-cpu-1x'
